import{A as b,S as m,N as E,a as q}from"./assets/vendor-tBkKSLTP.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const n of document.querySelectorAll('link[rel="modulepreload"]'))s(n);new MutationObserver(n=>{for(const i of n)if(i.type==="childList")for(const p of i.addedNodes)p.tagName==="LINK"&&p.rel==="modulepreload"&&s(p)}).observe(document,{childList:!0,subtree:!0});function o(n){const i={};return n.integrity&&(i.integrity=n.integrity),n.referrerPolicy&&(i.referrerPolicy=n.referrerPolicy),n.crossOrigin==="use-credentials"?i.credentials="include":n.crossOrigin==="anonymous"?i.credentials="omit":i.credentials="same-origin",i}function s(n){if(n.ep)return;n.ep=!0;const i=o(n);fetch(n.href,i)}})();const r="/test-of-project/assets/icons-52vXHJ8M.svg";new b(".info-content-list",{duration:300,showMultiple:!0,openOnInit:[0]});const I=[{title:"ABOUT ME",content:'<p class="first-text">I am Lloyd Jefferson, a talented programmer with extensive expert in software development. I have an understanding of different programming languages ​​and technologies, always ready to improve my skills. I always follow the latest trends and look for unconventional, creative solutions to problems. I have a high level of analytical skills and am able to effectively solve even the most difficult tasks encountered on the way.</p><p  class="first-text">Able to work both independently and in a team. I can effectively cooperate with colleagues, exchanging ideas and finding optimal solutions. Professional maturity allows you to calmly cope with challenges and stressful situations, while maintaining a high quality of work. I am always looking for opportunities for self-improvement. I actively study new technologies and practices to stay abreast of the latest innovations. I have a strong understanding of various programming languages, frameworks and architectural concepts that allow me to create efficient and scalable software.</p>'},{title:"ROLE",content:`<p>'Frontend development"</p><p>"HeadlessCMS,Wordpress"</p><p>"Blender(enjoy)</p>`},{title:"EDUCATION",content:"<p>2018 - 2019 / Frontend Development Diploma, GoIT IT School, New York</p><p>2019 - 2020 / Advanced Web Development Certificate, GoIT IT School, New York</p><p>2020 - 2022 / Advanced Blender Animation Techniques, Udemy</p>"}],x=document.querySelector(".info-content-list");function C(e){return e.map(({title:t,content:o},s)=>`
        <li class="info-content-item ${s===0?"is-active":""}">
        <h3 class="accordion-header info-title-acc"><p>${t}</p><button type="button" class="acc-btn"><svg class="about-acc-icon" width="18" height="18">
            <use href="${r}#icon-Icon-${s===0?"top":"bottom"}"></use></button></h3>
        <div class="accordion-content info-text-acc">${o}</div>
        </li>
            `).join("")}x.insertAdjacentHTML("beforeend",C(I));x.addEventListener("click",P);const y=document.querySelector(".info-content-item.is-active .accordion-content");y.style.maxHeight=y.scrollHeight+"px";function P(e){const t=e.target.closest(".acc-btn"),o=t.querySelector(".about-acc-icon");if(t){const s=t.closest(".info-content-item"),n=s.querySelector(".accordion-content");s.classList.toggle("is-active"),s.classList.contains("is-active")?n.style.maxHeight=n.scrollHeight+"px":n.style.maxHeight=0}o.classList.toggle("rotate180")}const T=["HTML/CSS","JavaScript","React","Node.js","React Native"," Soft skills"],$=document.querySelector(".skills-content-list");T.forEach(e=>{const t=document.createElement("li");t.classList.add("swiper-slide","slide-item-ab"),t.innerHTML=`<p class="swiper-ab-text">${e}</p>`,$.appendChild(t)});const A=new m(".skilla-about-swiper",{slidesPerView:6,slidesPerGroup:1,spaceBetween:0,modules:[E],loop:!0,navigation:{nextEl:".swiper-button-next-ab"},breakpoints:{320:{slidesPerView:"auto"},768:{slidesPerView:"auto"},1440:{slidesPerView:"auto"}}});A.update();document.querySelector(".swiper-button-next-ab").addEventListener("click",()=>{if(1399<window.innerWidth){const t=document.querySelector(".swiper-slide-active");let o=t.nextElementSibling;o||(o=document.querySelector(".swiper-slide:first-child")),t.classList.remove("swiper-slide-active"),o.classList.add("swiper-slide-active")}});const M=[{svgroot:`${r}#icon-user-01`,topic:"Expertise",text:"As a highly experienced developer, I have deep knowledge of programming and website development."},{svgroot:`${r}#icon-message-chat-circle`,topic:"Communication",text:"Understanding your needs and wants is my priority and I am always open to discussions and corrections."},{svgroot:`${r}#icon-brush-01`,topic:"Art",text:"Thanks to my creative nature, I am ready to accept challenges and help you bring your ideas to life. "},{svgroot:`${r}#icon-hourglass-02`,topic:"Urgent execution",text:"I understand how important time is to you. Ready to work quickly and efficiently, without reducing the quality of work."}],L=document.querySelector(".benefits-list");function H(e){return e.map(({svgroot:t,topic:o,text:s})=>`<li class="benefits-list-item">
          <svg class="benefits-icon" width="24" height="24">
            <use href="${t}"></use>
          </svg>
          <div>
            <h5 class="benefits-topic">${o}</h5>
            <p class="benefits-text">${s}</p>
          </div>
        </li>`).join("")}L.insertAdjacentHTML("beforeend",H(M));function j(e){const t=e.target.closest(".benefits-list-item");if(t){const o=t.querySelector(".benefits-topic").textContent;alert(`You clicked on: ${o}`)}}L.addEventListener("click",j);new m(".swiper",{direction:"horizontal",pagination:{el:".swiper-pagination"},navigation:{nextEl:".custom-button-next",prevEl:".custom-button-prev"}});new b(".faq-container",{duration:400,ariaEnabled:!0,showMultiple:!1,collapse:!0});const R=[{svgroot:"#icon-Icon-bottom",topic:"What programming languages ​​are most often used in your project?",text:"In the field of web development, there are various technologies and programming languages. Typically, this includes a combination of frontend (client side) and backend (server side) languages."},{svgroot:"#icon-Icon-bottom",topic:"What are the deadlines for the project?",text:"The terms of project implementation depend to a large extent on a number of factors, such as the scope of the project, its complexity, and the availability of resources. Determining exact deadlines is a difficult task, and it usually occurs during the planning phase of the project."},{svgroot:"#icon-Icon-bottom",topic:"What payment methods do you accept?",text:"Payment through credit and debit cards such as Visa, MasterCard, specialized electronic payment systems such as PayPal, as well as payments in cryptocurrencies such as Bitcoin, Ethereum and others."},{svgroot:"#icon-Icon-bottom",topic:"How can I contact you?",text:"In the field of web development, there are various technologies and programming languages. Typically, this includes a combination of frontend (client side) and backend (server side) languages."},{svgroot:"#icon-Icon-bottom",topic:"Do you provide advice or support?",text:"The terms of project implementation depend to a large extent on a number of factors, such as the scope of the project, its complexity, and the availability of resources. Determining exact deadlines is a difficult task, and it usually occurs during the planning phase of the project."},{svgroot:"#icon-Icon-bottom",topic:"What does the process of developing a software product look like from idea to implementation?",text:"Payment through credit and debit cards such as Visa, MasterCard, specialized electronic payment systems such as PayPal, as well as payments in cryptocurrencies such as Bitcoin, Ethereum and others."}],S=document.querySelector(".faq-container");function V(e){return e.map(({svgroot:t,topic:o,text:s},n)=>`
          <li class="faq ${n!==e.length-1,""}">
            <div class="faq-list-up">
               <h3 class="question">${o}</h3>
                 <svg class="faq-icon">
                   <use href="${r}${t}"></use>
                </svg>
           </div>
          <p class="faq-text">${s}</p>
          </li>`).join("")}S.insertAdjacentHTML("beforeend",V(R));function B(e){if(e.target.closest(".faq-icon")){const t=e.target.closest(".faq"),o=t.querySelector(".faq-text");t.classList.toggle("active"),t.classList.contains("active")?o.style.maxHeight=o.scrollHeight+"px":o.style.maxHeight=0}}S.addEventListener("click",B);const N=document.createElement("style");document.head.appendChild(N);const O=document.querySelector(".covers-content"),d=document.querySelectorAll(".covers-project"),W=document.querySelector(".container-reviews");function D(){for(let e=0;e<d.length;e++){const t=window.innerHeight,s=O.getBoundingClientRect().top,i=W.getBoundingClientRect().top;s<t*.9?d[e].classList.add("covers-animation"):d[e].classList.remove("covers-animation"),i<t*.1&&d[e].classList.remove("covers-animation")}}window.addEventListener("scroll",D);let u=0,a=0;async function f(e=0,t=4){try{const s=(await q.get("https://portfolio-js.b.goit.study/api/reviews")).data;if(u=s.length,u===0)J("Not found");else{const n=s.slice(e,e+t);F(n),k(t)}}catch{U("Failed to load reviews. Please try again.")}}function F(e){const t=document.querySelector(".swiper-wrapper.swiper-rew");t.innerHTML="",e.forEach(o=>{const s=document.createElement("li");s.classList.add("swiper-slide","review-item"),s.innerHTML=`
      <div class="review-item-content">
        <img class="image-reviews" src="${o.avatar_url}" alt="${o.author}">
        <b class="name-reviews">${o.author}</b>
        <p class="text-reviews">${o.review}</p>
      </div>`,t.appendChild(s)}),l.update()}function J(e){const t=document.querySelector(".swiper-wrapper.swiper-rew"),o=document.createElement("li");o.classList.add("swiper-slide","review-item"),o.textContent=e,t.appendChild(o)}function U(e){const t=document.querySelector(".error-popup");t.textContent=e,t.classList.add("active"),setTimeout(()=>{t.classList.remove("active")},3e3)}function k(e){const t=document.querySelector(".swiper-button-prev"),o=document.querySelector(".swiper-button-next");a===0?t.classList.add("swiper-button-disabled"):t.classList.remove("swiper-button-disabled"),a+e>=u?o.classList.add("swiper-button-disabled"):o.classList.remove("swiper-button-disabled")}const l=new m(".reviews-slider",{slidesPerView:4,spaceBetween:16,navigation:{nextEl:".swiper-button-next",prevEl:".swiper-button-prev"},keyboard:{enabled:!0,onlyInViewport:!0},simulateTouch:!0,touchRatio:1,touchAngle:45,grabCursor:!0,longSwipesMs:300,longSwipesRatio:.5,threshold:10,resistance:!0,resistanceRatio:.85,breakpoints:{320:{slidesPerView:1},768:{slidesPerView:2},1440:{slidesPerView:4}},on:{slideChange:()=>k(l.params.slidesPerView)}});document.querySelector(".swiper-button-next").addEventListener("click",()=>{const e=l.params.slidesPerView;a+e<u&&(a+=1,f(a,e))});document.querySelector(".swiper-button-prev").addEventListener("click",()=>{const e=l.params.slidesPerView;a>0&&(a-=1,f(a,e))});const G=l.params.slidesPerView;f(a,G);const h=document.querySelector(".footer-form"),Y=document.querySelector(".footer-form-button"),z=document.querySelector(".footer-close-button"),g=document.querySelector(".footer-backdrop"),v=document.querySelector(".footer-modal"),w="feedback-form-state";let c={email:"",comment:""};K();h.addEventListener("submit",Q);h.addEventListener("input",_);function _(e){const t=e.target.value.trim(),o=e.target.name.trim();c[o]=t,localStorage.setItem(w,JSON.stringify(c)),console.log(o,t)}function K(){let e=JSON.parse(localStorage.getItem(w));if(e)for(const t in e)h.elements[t].value=e[t],c[t]=e[t]}function Q(e){if(e.preventDefault(),!c.email||!c.message){alert("Fill please all fields");return}localStorage.removeItem(w),e.currentTarget.reset()}Y.addEventListener("click",function(){g.classList.add("is-open"),v.classList.add("is-open")});z.addEventListener("click",function(){g.classList.remove("is-open"),v.classList.add("is-open")});window.addEventListener("keydown",e=>{e.key==="Escape"&&(g.classList.remove("is-open"),v.classList.add("is-open"))});document.querySelector(".footer-backdrop .footer-modal").addEventListener("click",e=>{e._isClickWithInModal=!0});
//# sourceMappingURL=commonHelpers.js.map
